- name: Set up vcf-compression dev environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Install packages
      become: yes
      apt:
        name: [gcc, g++, make, libbz2-dev, liblzma-dev, libcurl4-openssl-dev]
        update_cache: yes

    - name: Clone htslib
      git:
        repo: https://github.com/samtools/htslib.git
        depth: 1
        dest: ~/htslib
    - name: Build htslib
      shell:
        chdir: ~/htslib
        cmd: make -j 4
        creates: ~/htslib/bgzip
    - name: Create ~/.local/bin
      file:
        path: ~/.local/bin
        state: directory
    - name: Add bgzip to path
      file:
        path: ~/.local/bin/bgzip
        state: link
        src: ~/htslib/bgzip
    - name: Add tabix to path
      file:
        path: ~/.local/bin/tabix
        state: link
        src: ~/htslib/tabix
    - name: Add ~/.local/bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$HOME/.local/bin:$PATH'


    # - name: Create R library
    #   file:
    #     path: ~/.local/lib/R
    #     state: directory
    # - name: Add ~/.local/bin to PATH
    #   lineinfile:
    #     path: ~/.profile
    #     line: 'export PATH=~/.local/bin:$PATH'

    # - name: Add jupyter-start.sh script to remote path
    #   copy:
    #     src: jupyter-start.sh
    #     dest: ~/.local/bin/jupyter-start.sh
    #     mode: u=rwx,g=r